### ISSUE TITLE
Info Window - Main Atlas

### ISSUE THREAD

**Issue by TheLemurKnows** [mephix/apnea-atlas#3]
I've been messing with the code in the button41_click function.  The queries all seem to be working fine.  I changed the preprocess function to each specific database, pool, divesite, etc (they were all preprocessEvent before). I also tried pushing the results of each query after process to a single array before sending the JSON to the html. It seems that the html is just not refreshing with this new data.  Did you add any code into the events html that allowed it to keep updating with each JSON?

**Comment by mephix** [comment]
Fixed by awaiting the queries before sending their results to the html.
