### ISSUE TITLE
Delete Schools database

### ISSUE THREAD

**Issue by mephix** [mephix/apnea-atlas#4]
@TheLemurKnows
is it time to delete the Schools database? 
Also can you put at least one School and one Instructor in the members database for testing purposes?

**Comment by TheLemurKnows** [comment]
The schools database cannot be deleted. I will insert now for testing

**Comment by TheLemurKnows** [comment]
Added and working. The only issue I see is that the dynamic page zoom is way too far in.  Can we zoom this out?

**Comment by mephix** [comment]
The zoom on which page(s)?
