### ISSUE TITLE
Atlas Zoomed too far out on page load

### ISSUE THREAD

**Issue by TheLemurKnows** [mephix/apnea-atlas#5]
When I open the live site, the atlas is showing a lot of extra space with no map pins. can we zoom this in some?
<img width="902" alt="screen shot 2018-04-23 at 6 29 16 pm" src="https://user-images.githubusercontent.com/12641532/39158198-4459a9c2-4724-11e8-9ce7-9b3cc5949690.png">

**Comment by mephix** [comment]
I limited zoom to 2 or greater. It might take a bit for the CDN to serve you the new copy but it has started working for me.
